/*
 * File: app/view/AddAddressPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.view.AddAddressPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.addaddresspanel',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        centered: true,
        height: 281,
        itemId: 'add_addressPanel',
        showAnimation: 'pop',
        width: 531,
        modal: true,
        items: [
            {
                xtype: 'fieldset',
                height: 261,
                itemId: 'address_data_fieldset1',
                title: 'Данные',
                items: [
                    {
                        xtype: 'selectfield',
                        target: 'add_address',
                        centered: false,
                        itemId: 'address_type_select',
                        label: 'Тип адреса',
                        name: 'id_address_type',
                        displayField: 'name',
                        store: 'address_type_store',
                        valueField: 'id_address_type'
                    },
                    {
                        xtype: 'textfield',
                        target: 'add_address',
                        itemId: 'address_name_textfield',
                        clearIcon: false,
                        label: 'Адрес',
                        name: 'name'
                    },
                    {
                        xtype: 'textfield',
                        target: 'add_address',
                        height: 116,
                        itemId: 'comment_textfield',
                        clearIcon: false,
                        label: 'Комментарий:',
                        name: 'comment'
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        itemId: 'add_address_bottom_toolbar',
                        items: [
                            {
                                xtype: 'button',
                                disabled: true,
                                docked: 'right',
                                itemId: 'add_btn',
                                text: 'Добавить'
                            },
                            {
                                xtype: 'button',
                                docked: 'right',
                                itemId: 'cancel_btn',
                                text: 'Отмена'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});