/*
 * File: app/view/AddressPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.view.AddressPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.addresspanel',

    requires: [
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.Select'
    ],

    config: {
        centered: true,
        height: 572,
        itemId: 'addressPanel',
        showAnimation: 'pop',
        width: 785,
        modal: true,
        items: [
            {
                xtype: 'list',
                docked: 'left',
                itemId: 'address_list',
                width: 278,
                itemTpl: [
                    '<div class="address"> {name}<br>{comment}<br> </div>'
                ],
                store: 'address_store',
                striped: true,
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'add_address_btn',
                                iconCls: 'add',
                                text: 'Добавить'
                            },
                            {
                                xtype: 'button',
                                disabled: true,
                                id: 'delete_address_btn',
                                iconCls: 'delete',
                                text: 'Удалить'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                height: 261,
                itemId: 'address_data_fieldset',
                title: 'Данные',
                items: [
                    {
                        xtype: 'selectfield',
                        target: 'edit_address',
                        itemId: 'address_type_select',
                        label: 'Тип адреса',
                        name: 'id_address_type',
                        autoSelect: false,
                        displayField: 'name',
                        store: 'address_type_store',
                        valueField: 'id_address_type'
                    },
                    {
                        xtype: 'textfield',
                        target: 'edit_address',
                        itemId: 'address_name_textfield',
                        clearIcon: false,
                        label: 'Адрес',
                        name: 'name'
                    },
                    {
                        xtype: 'textfield',
                        target: 'edit_address',
                        height: 116,
                        itemId: 'comment_textfield',
                        clearIcon: false,
                        label: 'Комментарий:',
                        name: 'comment'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 45,
                items: [
                    {
                        xtype: 'container',
                        docked: 'right',
                        items: [
                            {
                                xtype: 'button',
                                disabled: true,
                                docked: 'top',
                                itemId: 'save_address_btn',
                                iconCls: 'bookmarks',
                                text: 'Сохранить'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'container',
                        docked: 'right',
                        items: [
                            {
                                xtype: 'button',
                                t: 's',
                                docked: 'right',
                                itemId: 'id_ok_addr_btn',
                                width: 100,
                                text: 'OK'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});