/*
 * File: app/view/CatalogMenu.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.view.CatalogMenu', {
    extend: 'Ext.Panel',
    alias: 'widget.catalogmenu',

    requires: [
        'Ext.Button'
    ],

    config: {
        centered: true,
        hidden: true,
        itemId: 'catalogMenu',
        padding: 10,
        hideOnMaskTap: true,
        modal: true,
        items: [
            {
                xtype: 'button',
                itemId: 'item_type_groups_btn',
                margin: 15,
                iconCls: 'home',
                text: 'Группы одежды'
            },
            {
                xtype: 'button',
                itemId: 'item_types_btn',
                margin: 15,
                iconCls: 'home',
                text: 'Наименования одежды'
            }
        ]
    }

});