/*
 * File: app/view/ClientPanelExt.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.view.ClientPanelExt', {
    extend: 'Ext.Panel',
    alias: 'widget.clientpanelext',

    requires: [
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.field.Select',
        'Ext.field.Search'
    ],

    config: {
        itemId: 'clientPanelExt',
        layout: 'vbox',
        items: [
            {
                xtype: 'list',
                flex: 1,
                height: 245,
                itemId: 'client_list',
                itemTpl: [
                    '<div class="client"> {surname}<br>{name}<br>{patronymic} <br><b>Тел.:{phone}</b><br> </div>'
                ],
                store: 'client_store',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        ui: 'light',
                        items: [
                            {
                                xtype: 'container',
                                items: [
                                    {
                                        xtype: 'button',
                                        docked: 'left',
                                        itemId: 'add_client_btn',
                                        width: 106,
                                        iconCls: 'add',
                                        text: 'Добавить'
                                    },
                                    {
                                        xtype: 'button',
                                        disabled: true,
                                        docked: 'left',
                                        itemId: 'delete_client_btn',
                                        width: 108,
                                        iconCls: 'delete',
                                        text: 'Удалить'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                docked: 'right',
                                items: [
                                    {
                                        xtype: 'button',
                                        disabled: true,
                                        docked: 'right',
                                        itemId: 'menu_client_btn',
                                        iconCls: 'action',
                                        text: 'Меню клиента'
                                    },
                                    {
                                        xtype: 'button',
                                        docked: 'right',
                                        hidden: true,
                                        itemId: 'cancle_btn',
                                        iconCls: 'home',
                                        text: 'Отмена'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'container',
                                width: 676,
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        itemId: 'filter_field',
                                        label: '',
                                        displayField: 'name',
                                        store: 'client_filter_store',
                                        valueField: 'field_name'
                                    },
                                    {
                                        xtype: 'searchfield',
                                        itemId: 'search_field',
                                        width: 389,
                                        clearIcon: false,
                                        label: ''
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});