/*
 * File: app/view/EditItemTypesPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.view.EditItemTypesPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.edititemtypepanel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.Checkbox',
        'Ext.field.Select'
    ],

    config: {
        centered: true,
        height: 562,
        itemId: 'editItemTypesPanel',
        width: 560,
        modal: true,
        items: [
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'container',
                        docked: 'right',
                        width: 250,
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'button',
                                flex: 1,
                                itemId: 'ok_btn',
                                iconCls: 'action',
                                text: 'OK'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                itemId: 'cancle_btn',
                                iconCls: 'home',
                                text: 'Отмена'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                height: 477,
                title: 'Данные позиции:',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'name_fld',
                        clearIcon: false,
                        label: 'Наименование:'
                    },
                    {
                        xtype: 'checkboxfield',
                        itemId: 'peace_only_fld',
                        label: 'Только штучно:'
                    },
                    {
                        xtype: 'checkboxfield',
                        itemId: 'hanger_fld',
                        label: 'С вешалкой:'
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'total_time_in_second_fld',
                        clearIcon: false,
                        label: 'Тайминг (в сек.):'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'group_fld',
                        label: 'Группа:',
                        displayField: 'name',
                        store: 'item_type_groups_store',
                        valueField: 'id_item_type_group'
                    },
                    {
                        xtype: 'textfield',
                        disabled: true,
                        itemId: 'cur_price_fld',
                        clearIcon: false,
                        label: 'Текущий прайс:'
                    },
                    {
                        xtype: 'textfield',
                        disabled: true,
                        itemId: 'cur_action_price_fld',
                        clearIcon: false,
                        label: 'Текущая акция:'
                    },
                    {
                        xtype: 'textfield',
                        height: 102,
                        itemId: 'comment_fld',
                        clearIcon: false,
                        label: 'Комментарии:'
                    }
                ]
            }
        ]
    }

});