/*
 * File: app/view/EditItemTypeGroupsPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.view.EditItemTypeGroupsPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.edititemtypegropupspanel',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Text',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        centered: true,
        height: 276,
        itemId: 'editItemTypeGroupsPanel',
        width: 527,
        modal: true,
        items: [
            {
                xtype: 'fieldset',
                title: 'Данные группы:',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'item_type_group_name',
                        clearIcon: false,
                        label: 'Имя группа'
                    },
                    {
                        xtype: 'textfield',
                        height: 103,
                        itemId: 'item_type_group_comment',
                        clearIcon: false,
                        label: 'Комментарии'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'container',
                        docked: 'right',
                        width: 250,
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'button',
                                flex: 1,
                                disabled: true,
                                itemId: 'ok_btn',
                                width: 92,
                                iconCls: 'action',
                                text: 'OK'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                itemId: 'cancle_btn',
                                iconCls: 'home',
                                text: 'Отмена'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});