/*
 * File: app/view/ItemGroupsPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.view.ItemGroupsPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.itemgroupspanel',

    requires: [
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.Text'
    ],

    config: {
        itemId: 'itemGroupsPanel',
        items: [
            {
                xtype: 'list',
                disabled: false,
                docked: 'left',
                itemId: 'itemgroup_list',
                width: 329,
                itemTpl: [
                    '<div class="user"> {name}</div>'
                ],
                striped: true,
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                flex: 1,
                                itemId: 'add_itemgroup_button',
                                width: 125,
                                iconCls: 'add',
                                text: 'Добавить'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                disabled: true,
                                itemId: 'delete_itemgroup_button',
                                width: 125,
                                iconCls: 'delete',
                                text: 'Удалить'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'itemgroup_data_fieldset',
                title: 'Данные',
                items: [
                    {
                        xtype: 'textfield',
                        target: 'edit_itemgroup',
                        itemId: 'itemgroup_name_textfield',
                        clearIcon: false,
                        label: 'Наименование',
                        name: 'name'
                    },
                    {
                        xtype: 'textfield',
                        target: 'edit_itemgroup',
                        height: 116,
                        itemId: 'itemgroup_comment_textfield',
                        clearIcon: false,
                        label: 'Комментарии',
                        name: 'comment'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 41,
                itemId: 'itemgroup_toolbar',
                items: [
                    {
                        xtype: 'button',
                        flex: 1,
                        disabled: true,
                        docked: 'right',
                        itemId: 'itemgroup_save_button',
                        width: 133,
                        iconCls: 'bookmarks',
                        text: 'Сохранить'
                    }
                ]
            }
        ]
    }

});