/*
 * File: app/view/ItemTypesPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.view.ItemTypesPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.itemtypespanel',

    requires: [
        'Ext.dataview.NestedList',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        centered: true,
        height: 600,
        itemId: 'itemTypesPanel',
        width: 635,
        layout: 'fit',
        modal: true,
        items: [
            {
                xtype: 'nestedlist',
                itemId: 'item_types_list',
                scrollable: true,
                backText: 'Назад',
                displayField: 'name',
                emptyText: 'В группе нет позиций',
                store: 'item_type_full_tree_store'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'container',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'container',
                                layout: 'fit',
                                items: [
                                    {
                                        xtype: 'button',
                                        itemId: 'add_btn',
                                        margin: '1px 1px 1px 1px',
                                        iconCls: 'add',
                                        text: 'Добавить'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        margin: 0,
                                        layout: 'vbox',
                                        items: [
                                            {
                                                xtype: 'button',
                                                disabled: true,
                                                itemId: 'change_item_btn',
                                                margin: '1px 1px 1px 1px',
                                                iconCls: 'compose',
                                                text: 'Изменить позицию'
                                            },
                                            {
                                                xtype: 'button',
                                                disabled: true,
                                                itemId: 'change_group_btn',
                                                margin: '1px 1px 1px 1px',
                                                iconCls: 'compose',
                                                text: 'Изменить группу'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        items: [
                                            {
                                                xtype: 'button',
                                                disabled: true,
                                                itemId: 'delete_item_btn',
                                                margin: '1px 1px 1px 1px',
                                                iconCls: 'delete',
                                                text: 'Удалить позицию'
                                            },
                                            {
                                                xtype: 'button',
                                                disabled: true,
                                                itemId: 'delete_group_btn',
                                                margin: '1px 1px 1px 1px',
                                                iconCls: 'delete',
                                                text: 'Удалить группу'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'container',
                        docked: 'right',
                        width: 120,
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'button',
                                flex: 1,
                                itemId: 'cancle_btn',
                                iconCls: 'home',
                                text: 'Отмена'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});