/*
 * File: app/view/OrderMenu.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.view.OrderMenu', {
    extend: 'Ext.Panel',
    alias: 'widget.addordermenu',

    requires: [
        'Ext.Button'
    ],

    config: {
        centered: true,
        hidden: true,
        itemId: 'addorderMenu',
        padding: 10,
        hideOnMaskTap: true,
        modal: true,
        items: [
            {
                xtype: 'button',
                disabled: false,
                itemId: 'create_contract',
                margin: 15,
                iconCls: 'compose',
                text: 'Договор'
            },
            {
                xtype: 'button',
                disabled: false,
                itemId: 'create_docs',
                margin: 15,
                iconCls: 'compose',
                text: 'Сопроводительные'
            },
            {
                xtype: 'button',
                disabled: false,
                itemId: 'create_lines',
                margin: 15,
                iconCls: 'compose',
                text: 'Ленточки'
            },
            {
                xtype: 'button',
                disabled: false,
                itemId: 'create_lines_container_stickers',
                margin: 15,
                iconCls: 'compose',
                text: 'Для контейнеров'
            },
            {
                xtype: 'button',
                disabled: false,
                itemId: 'show_video',
                margin: 15,
                iconCls: 'compose',
                text: 'Видео'
            }
        ]
    }

});