/*
 * File: app/view/OrderTaskPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.view.OrderTaskPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.ordertaskpanel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.field.Select'
    ],

    config: {
        centered: true,
        height: 715,
        itemId: 'orderTaskPanel',
        width: 654,
        layout: 'fit',
        modal: true,
        items: [
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'container',
                        docked: 'right',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'cancel_btn',
                                text: 'Отмена'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'order_list',
                mode: 'MULTI',
                itemTpl: [
                    '<div>Заказ номер {id_order} <br> от {date_create} <br> для {client_name} </div>'
                ],
                store: 'order_by_status_store',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'calc_from_time',
                                text: 'Расчет по времени'
                            },
                            {
                                xtype: 'button',
                                itemId: 'create_for_selected',
                                text: 'По выбранным'
                            }
                        ]
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'selectfield',
                                flex: 1,
                                itemId: 'executor_fld',
                                width: 409,
                                label: 'Сотрудник:',
                                displayField: 'full_user_name',
                                store: 'executor_store',
                                valueField: 'id_user'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});