/*
 * File: app/view/OrderPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.view.OrderPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.orderpanel',

    requires: [
        'Ext.dataview.List',
        'Ext.Toolbar',
        'Ext.field.Search',
        'Ext.Button',
        'Ext.XTemplate',
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.field.Number',
        'Ext.field.Checkbox'
    ],

    config: {
        itemId: 'orderPanel',
        items: [
            {
                xtype: 'list',
                docked: 'left',
                itemId: 'id_order_list',
                width: 305,
                itemTpl: [
                    '<div>Заказ номер {id_order}</div>'
                ],
                store: 'order_store',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'searchfield',
                                        itemId: 'id_search_order',
                                        label: 'Поиск:'
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'search_menu',
                                        iconCls: 'search',
                                        text: ''
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'button',
                                flex: 1,
                                itemId: 'add_order_button',
                                width: 125,
                                iconCls: 'add',
                                text: 'Добавить'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                disabled: true,
                                itemId: 'delete_order_button',
                                width: 125,
                                iconCls: 'delete',
                                text: 'Удалить'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 41,
                itemId: 'order_toolbar',
                items: [
                    {
                        xtype: 'button',
                        flex: 1,
                        disabled: true,
                        docked: 'right',
                        itemId: 'order_save_button',
                        width: 133,
                        iconCls: 'bookmarks',
                        text: 'Сохранить'
                    },
                    {
                        xtype: 'button',
                        docked: 'left',
                        itemId: 'task_order_button',
                        width: 91,
                        iconCls: 'info',
                        text: 'З-Н'
                    },
                    {
                        xtype: 'button',
                        flex: 1,
                        disabled: true,
                        docked: 'left',
                        itemId: 'order_menu_button',
                        width: 101,
                        iconCls: 'more',
                        text: 'Меню'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                docked: 'top',
                height: 708,
                scrollable: true,
                title: 'Информация о заказе',
                items: [
                    {
                        xtype: 'selectfield',
                        target: 'add_order',
                        disabled: false,
                        itemId: 'id_order_status',
                        label: 'Статус:',
                        name: 'id_status',
                        autoSelect: false,
                        displayField: 'name',
                        store: 'order_status_store',
                        valueField: 'id_status'
                    },
                    {
                        xtype: 'selectfield',
                        target: 'add_order',
                        disabled: false,
                        itemId: 'id_order_executor',
                        label: 'Исполнитель:',
                        name: 'id_executor',
                        autoSelect: false,
                        displayField: 'name',
                        store: 'user_store',
                        valueField: 'id_user'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'id_order_client',
                        label: 'Клиент:',
                        name: 'id_client',
                        autoSelect: false,
                        displayField: 'name',
                        store: 'client_store',
                        valueField: 'id_client'
                    },
                    {
                        xtype: 'numberfield',
                        itemId: 'id_ticket_number_field',
                        clearIcon: false,
                        label: 'Номер квитанции:',
                        name: 'ticket_number'
                    },
                    {
                        xtype: 'numberfield',
                        itemId: 'id_container_count_field',
                        clearIcon: false,
                        label: 'Количество контейнеров:',
                        name: 'cont_count'
                    },
                    {
                        xtype: 'numberfield',
                        itemId: 'id_weight_field',
                        clearIcon: false,
                        label: 'Вес текстиль:',
                        name: 'weight_home'
                    },
                    {
                        xtype: 'numberfield',
                        itemId: 'id_weight_dress',
                        clearIcon: false,
                        label: 'Вес одежда:',
                        name: 'weight_dress'
                    },
                    {
                        xtype: 'selectfield',
                        target: 'add_order',
                        disabled: false,
                        itemId: 'id_action_order',
                        label: 'Акция на заказ:',
                        name: 'id_action',
                        autoSelect: false,
                        displayField: 'action_name',
                        store: 'order_actions_store',
                        valueField: 'id_action'
                    },
                    {
                        xtype: 'checkboxfield',
                        itemId: 'id_white_field',
                        label: 'Белый:',
                        name: 'is_white'
                    },
                    {
                        xtype: 'textfield',
                        height: 50,
                        itemId: 'id_comment_field',
                        clearIcon: false,
                        label: 'Комментарии:',
                        name: 'comment'
                    },
                    {
                        xtype: 'textfield',
                        height: 92,
                        itemId: 'id_addition_info_field',
                        clearIcon: false,
                        label: 'Дополнительная информация о заказе:'
                    }
                ]
            }
        ]
    }

});