/*
 * File: app/view/ReportsMenuPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.view.ReportsMenuPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.reportsmenupanel',

    requires: [
        'Ext.Button'
    ],

    config: {
        centered: true,
        itemId: 'reportsMenuPanel',
        padding: 15,
        hideOnMaskTap: true,
        modal: true,
        items: [
            {
                xtype: 'button',
                itemId: 'done_report_btn',
                text: 'Готовые заказы'
            }
        ]
    }

});