/*
 * File: app/view/SearchOrderMenu.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.view.SearchOrderMenu', {
    extend: 'Ext.Panel',
    alias: 'widget.seachordermenu',

    requires: [
        'Ext.Button'
    ],

    config: {
        centered: true,
        hidden: true,
        itemId: 'searchOrderMenu',
        padding: 10,
        hideOnMaskTap: true,
        modal: true,
        items: [
            {
                xtype: 'button',
                itemId: 'all_orders',
                margin: 15,
                iconCls: 'team',
                text: 'Все'
            },
            {
                xtype: 'button',
                itemId: 'new_orders',
                margin: 15,
                iconCls: 'team',
                text: 'Новые'
            },
            {
                xtype: 'button',
                itemId: 'finished_orders',
                margin: 15,
                iconCls: 'team',
                text: 'Готовые'
            },
            {
                xtype: 'button',
                itemId: 'closed_orders',
                margin: 15,
                iconCls: 'team',
                text: 'Закрытые'
            }
        ]
    }

});