/*
 * File: app/view/UserPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.view.UserPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.userpanel',

    requires: [
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.form.FieldSet',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.Toolbar'
    ],

    config: {
        itemId: 'userPanel',
        items: [
            {
                xtype: 'list',
                disabled: false,
                docked: 'left',
                itemId: 'user_list',
                width: 329,
                itemTpl: [
                    '<div class="user"> {nick}<br>{initials}<br> </div>'
                ],
                store: 'user_store',
                striped: true
            },
            {
                xtype: 'fieldset',
                itemId: 'user_data_fieldset',
                title: 'Данные',
                items: [
                    {
                        xtype: 'textfield',
                        target: 'edit_user',
                        itemId: 'user_nick_textfield',
                        clearIcon: false,
                        label: 'Ник',
                        name: 'nick'
                    },
                    {
                        xtype: 'textfield',
                        target: 'edit_user',
                        itemId: 'user_name_textfield',
                        clearIcon: false,
                        label: 'Имя',
                        name: 'name'
                    },
                    {
                        xtype: 'textfield',
                        target: 'edit_user',
                        itemId: 'user_patronymic_textfield',
                        clearIcon: false,
                        label: 'Отчество',
                        name: 'patronymic'
                    },
                    {
                        xtype: 'textfield',
                        target: 'edit_user',
                        itemId: 'user_surname_textfield',
                        clearIcon: false,
                        label: 'Фамилия',
                        name: 'surname'
                    },
                    {
                        xtype: 'datepickerfield',
                        target: 'edit_user',
                        disabled: true,
                        itemId: 'user_date_create_textfield',
                        label: ' Дата создания',
                        name: 'date_create',
                        placeHolder: 'mm/dd/yyyy'
                    },
                    {
                        xtype: 'textfield',
                        target: 'edit_user',
                        height: 116,
                        itemId: 'user_comment_textfield',
                        label: 'Комментарии',
                        name: 'comment'
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'container',
                                docked: 'right',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'button',
                                        docked: 'right',
                                        itemId: 'add_user_button',
                                        ui: 'confirm',
                                        width: 125,
                                        iconCls: 'add',
                                        text: 'Добавить'
                                    },
                                    {
                                        xtype: 'button',
                                        disabled: true,
                                        docked: 'right',
                                        itemId: 'delete_user_button',
                                        ui: 'decline',
                                        width: 125,
                                        iconCls: 'delete',
                                        text: 'Удалить'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                height: 41,
                itemId: 'user_toolbar',
                items: [
                    {
                        xtype: 'button',
                        flex: 1,
                        disabled: true,
                        docked: 'right',
                        itemId: 'user_save_button',
                        width: 133,
                        iconCls: 'bookmarks',
                        text: 'Сохранить'
                    },
                    {
                        xtype: 'button',
                        flex: 1,
                        disabled: true,
                        docked: 'left',
                        itemId: 'usermenu_button',
                        width: 101,
                        iconCls: 'more',
                        text: 'Меню'
                    }
                ]
            }
        ]
    }

});