/*
 * File: app/model/item_type_model.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.model.item_type_model', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'id_item_type',
                type: 'int'
            },
            {
                name: 'is_home_weight',
                type: 'int'
            },
            {
                name: 'is_only_piece',
                type: 'int'
            },
            {
                name: 'name',
                type: 'string'
            },
            {
                name: 'comment',
                type: 'string'
            }
        ]
    }
});