/*
 * File: app/model/order_model.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.model.order_model', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'id_order',
                type: 'int'
            },
            {
                name: 'id_action',
                type: 'int'
            },
            {
                name: 'id_client',
                type: 'int'
            },
            {
                name: 'id_executor',
                type: 'int'
            },
            {
                name: 'date_create',
                type: 'date'
            },
            {
                name: 'cont_count',
                type: 'int'
            },
            {
                name: 'weight_home',
                type: 'float'
            },
            {
                name: 'weight_dress',
                type: 'float'
            },
            {
                name: 'ticket_number',
                type: 'int'
            },
            {
                name: 'is_white',
                type: 'boolean'
            },
            {
                name: 'id_status',
                type: 'int'
            },
            {
                name: 'comment',
                type: 'string'
            }
        ]
    }
});