/*
 * File: app/model/order_detail_model.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.model.order_detail_model', {
    extend: 'Ext.data.Model',
    alias: 'model.orderdetail',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'id_order_detail',
                type: 'int'
            },
            {
                name: 'number',
                type: 'int'
            },
            {
                name: 'id_order',
                type: 'int'
            },
            {
                name: 'id_item_type',
                type: 'int'
            },
            {
                name: 'item_type_name',
                type: 'string'
            },
            {
                name: 'id_item_type_group',
                type: 'int'
            },
            {
                name: 'count',
                type: 'int'
            },
            {
                name: 'id_color',
                type: 'int'
            },
            {
                name: 'color',
                type: 'string'
            },
            {
                name: 'id_gender',
                type: 'int'
            },
            {
                name: 'gender',
                type: 'string'
            },
            {
                name: 'wear',
                type: 'float'
            },
            {
                name: 'id_price',
                type: 'int'
            },
            {
                name: 'price_type',
                type: 'string'
            },
            {
                name: 'price',
                type: 'float'
            },
            {
                name: 'result_price',
                type: 'float'
            },
            {
                name: 'price_dimension',
                type: 'string'
            },
            {
                name: 'discount',
                type: 'float'
            },
            {
                name: 'id_action',
                type: 'int'
            },
            {
                name: 'action_name',
                type: 'string'
            },
            {
                name: 'action_type',
                type: 'string'
            },
            {
                name: 'action_value',
                type: 'float'
            },
            {
                name: 'result_action_name',
                type: 'string'
            },
            {
                name: 'is_lable',
                type: 'int'
            },
            {
                name: 'hanger',
                type: 'int'
            },
            {
                name: 'comment',
                type: 'string'
            },
            {
                name: 'is_home_weight',
                type: 'int'
            },
            {
                name: 'wear_name',
                type: 'string'
            }
        ]
    }
});