/*
 * File: app/controller/add_address_controller.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.controller.add_address_controller', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            addAddressPanel: {
                selector: 'panel#add_addressPanel',
                xtype: 'addaddresspanel'
            },
            cancel_btn: {
                selector: 'panel#add_addressPanel button[itemId=cancel_btn]',
                xtype: 'Ext.Button'
            },
            add_btn: {
                selector: 'panel#add_addressPanel button[itemId=add_btn]',
                xtype: 'Ext.Button'
            },
            address_type_select: {
                selector: 'panel#add_addressPanel selectfield[itemId=address_type_select]',
                xtype: 'Ext.field.Select'
            },
            address_name_fld: {
                selector: 'panel#add_addressPanel  textfield[itemId=address_name_textfield]',
                xtype: 'Ext.field.Text'
            },
            comment_fld: {
                selector: 'panel#add_addressPanel  textfield[itemId=comment_textfield]',
                xtype: 'Ext.field.Text'
            }
        },

        control: {
            "cancel_btn": {
                tap: 'cancle_btn_tap'
            },
            "address_type_select": {
                change: 'addr_type_change'
            },
            "panel#add_addressPanel  textfield": {
                keyup: 'address_data_chenge'
            },
            "add_btn": {
                tap: 'add_address_btn_tap'
            },
            "addAddressPanel": {
                show: 'onAddressPanelShow'
            }
        }
    },

    cancle_btn_tap: function(button, e, eOpts) {
        this.close_add_address_form();
    },

    addr_type_change: function(selectfield, newValue, oldValue, eOpts) {
        this.check_all_fields();
    },

    address_data_chenge: function(textfield, e, eOpts) {
        this.check_all_fields();
    },

    add_address_btn_tap: function(button, e, eOpts) {
        var address_type = this.getAddress_type_select().getValue();
        var name = this.getAddress_name_fld().getValue();
        var comment = this.getComment_fld().getValue();



        this.add_address (address_type, name, comment);
    },

    onAddressPanelShow: function(component, eOpts) {
        this.id_owner = this.getApplication().getController('address_panel_controller').get_address_list_owner_id();
        this.owner_type = this.getApplication().getController('address_panel_controller').get_address_list_owner_type();

    },

    close_add_address_form: function() {
        var add_address_panel = this.getAddAddressPanel();
        add_address_panel.destroy();


        this.getApplication().getController('address_panel_controller').update_address_list();
    },

    set_buttons_disable: function(disable) {
        var add_btn = this.getAdd_btn();
        add_btn.setDisabled(disable);
    },

    check_all_fields: function() {
        var address_type = this.getAddress_type_select().getValue();
        var name = this.getAddress_name_fld().getValue();
        var comment = this.getComment_fld().getValue();


        if (address_type && name.length > 0)
            this.set_buttons_disable (false);
        else
            this.set_buttons_disable (true);

    },

    add_address: function(id_address_type, name, comment) {
        var t = this;

        Ext.data.JsonP.request(
            {
                url: GlobalVars.url_setting + 'php/base_functional.php',
                params:
                {
                    function_name	: 'add_address',
                    id_owner		: t.id_owner,
                    owner_type		: t.owner_type,
                    id_address_type	: id_address_type,
                    name			: name,
                    comment			: comment,
                    format			: 'json'
                },
                callbackKey: 'callback',
                scope: this,
                success: function (result)
                {
                    Ext.Msg.alert('Iron', result.text);

                    if (result.result == 'ok')
                        t.close_add_address_form ();

                }
            });



    }

});