/*
 * File: app/controller/add_client_controller.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.controller.add_client_controller', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            addClientPanel: 'panel#addClientPanel',
            client_name: 'panel#addClientPanel textfield[itemId=client_name_textfield]',
            client_patronymic: 'panel#addClientPanel textfield[itemId=client_patronymic_textfield]',
            client_surname: 'panel#addClientPanel textfield[itemId=client_surname_textfield]',
            client_gender: 'panel#addClientPanel selectfield[itemId=client_gender_field]',
            client_birthday: 'panel#addClientPanel textfield[itemId=birthday_textfield]',
            client_comment: 'panel#addClientPanel textfield[itemId=client_comment_textfield]',
            add_btn: 'panel#addClientPanel button[itemId=add_btn]',
            cancel_btn: 'panel#addClientPanel button[itemId=cancel_btn]'
        },

        control: {
            "panel#addClientPanel  textfield[target='add_client']": {
                keyup: 'textdata_changed',
                change: 'gender_changed'
            },
            "cancel_btn": {
                tap: 'cancle_btn_tap'
            },
            "add_btn": {
                tap: 'add_client_tap'
            }
        }
    },

    textdata_changed: function(textfield, e, eOpts) {
        this.check_all_fields();
    },

    gender_changed: function(selectfield, newValue, oldValue, eOpts) {
        this.check_all_fields();
    },

    cancle_btn_tap: function(button, e, eOpts) {
        this.close_add_client_form();
    },

    add_client_tap: function(button, e, eOpts) {
        var id_gender = this.getClient_gender().getValue();
        var name = this.getClient_name().getValue();
        var surname = this.getClient_surname().getValue();
        var patronymic = this.getClient_patronymic().getValue();
        var birthday = this.getClient_birthday().getValue();
        var comment = this.getClient_comment().getValue();



        this.add_client(name, surname, patronymic, id_gender, birthday, comment);
    },

    update_gender_list: function() {

    },

    close_add_client_form: function() {
        var add_client_panel = this.getAddClientPanel();
        add_client_panel.destroy();


        this.getApplication().getController('client_panel_controller').update_client_list();
    },

    check_all_fields: function() {
        var id_gender = this.getClient_gender().getValue();
        var name = this.getClient_name().getValue();
        var surname = this.getClient_surname().getValue();
        var patronymic = this.getClient_patronymic().getValue();
        var birthday = this.getClient_birthday().getValue();
        var comment = this.getClient_comment().getValue();


        if (birthday && id_gender && name.length > 0 && surname.length >0 && patronymic.length >0)
            this.set_buttons_disable (false);
        else
            this.set_buttons_disable (true);

    },

    set_buttons_disable: function(disable) {
        var add_btn = this.getAdd_btn();
        add_btn.setDisabled(disable);
    },

    add_client: function(name, surname, patronymic, id_gender, birthday, comment) {
        var t = this;

        Ext.data.JsonP.request(
            {
                url: GlobalVars.url_setting + 'php/base_functional.php',
                params:
                {
                    function_name	: 'add_client',
                    name			: name,
                    surname			: surname,
                    patronymic		: patronymic,
                    id_gender		: id_gender,
                    birthday		: birthday,
                    comment			: comment,
                    format			: 'json'
                },
                callbackKey: 'callback',
                scope: this,
                success: function (result)
                {
                    Ext.Msg.alert('Iron', result.text);

                    if (result.result == 'ok')
                        t.close_add_client_form ();

                }
            });



    }

});