/*
 * File: app/controller/add_phone_controller.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.controller.add_phone_controller', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            addPhonePanel: 'panel#addPhonePanel',
            phone_field: 'panel#addPhonePanel textfield[itemId=id_phone_field]',
            phone_comment_field: 'panel#addPhonePanel textfield[itemId=id_phone_comment_field]',
            primary_phone_checkbox: 'panel#addPhonePanel checkboxfield[itemId=id_primary_phone_checkbox]',
            add_btn: 'panel#addPhonePanel button[itemId=add_btn]',
            cancel_btn: 'panel#addPhonePanel button[itemId=cancel_btn]'
        },

        control: {
            "addPhonePanel": {
                show: 'onPhonePanelShow'
            },
            "cancel_btn": {
                tap: 'cancle_btn_tap'
            },
            "primary_phone_checkbox": {
                change: 'is_primary_change'
            },
            "panel#addPhonePanel  textfield": {
                keyup: 'phone_data_chenge'
            },
            "add_btn": {
                tap: 'add_phone_btn'
            }
        }
    },

    onPhonePanelShow: function(component, eOpts) {
        this.id_owner = this.getApplication().getController('phone_panel_controller').get_phone_list_owner_id();
        this.owner_type = this.getApplication().getController('phone_panel_controller').get_phone_list_owner_type();

    },

    cancle_btn_tap: function(button, e, eOpts) {
        this.close_add_phone_form();
    },

    is_primary_change: function(checkboxfield, newValue, oldValue, eOpts) {
        this.check_all_fields();
    },

    phone_data_chenge: function(textfield, e, eOpts) {
        this.check_all_fields();
    },

    add_phone_btn: function(button, e, eOpts) {
        var phone = this.getPhone_field().getValue();
        var is_primary = this.getPrimary_phone_checkbox().getChecked();
        var comment = this.getPhone_comment_field().getValue();


        this.add_phone (phone, comment, is_primary);
    },

    close_add_phone_form: function() {
        var add_phone_panel = this.getAddPhonePanel();
        add_phone_panel.destroy();

        this.getApplication().getController('phone_panel_controller').update_phone_list();
    },

    set_buttons_disable: function(disable) {
        var add_btn = this.getAdd_btn();
        add_btn.setDisabled(disable);
    },

    check_all_fields: function() {
        var phone_field= this.getPhone_field().getValue();
        var comment = this.getPhone_comment_field().getValue();


        if (phone_field.length > 0)
            this.set_buttons_disable (false);
        else
            this.set_buttons_disable (true);

    },

    add_phone: function(phone, comment, is_primary) {
        var t = this;

        var is_primary_ = 0;

        if	(is_primary)
            is_primary_ = 1;

        console.log(t.owner_type);

        Ext.data.JsonP.request(
            {
                url: GlobalVars.url_setting + 'php/base_functional.php',
                params:
                {
                    function_name	: 'add_phone',
                    id_owner		: t.id_owner,
                    owner_type		: t.owner_type,
                    phone			: phone,
                    is_primary		: is_primary_,
                    comment			: comment,
                    format: 'json'
                },
                callbackKey: 'callback',
                scope: this,
                success: function (result)
                {
                    Ext.Msg.alert('Iron', result.text);

                    if (result.result == 'ok')
                        t.close_add_phone_form ();

                }
            });



    }

});