/*
 * File: app/controller/search_order_menu_controller.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Iron.controller.search_order_menu_controller', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            searchOrderMenu: 'panel#searchOrderMenu',
            finished_orders: 'panel#searchOrderMenu button[itemId=finished_orders]',
            new_orders: 'panel#searchOrderMenu button[itemId=new_orders]',
            closed_orders: 'panel#searchOrderMenu button[itemId=closed_orders]',
            all_orders: 'panel#searchOrderMenu button[itemId=all_orders]'
        },

        control: {
            "finished_orders": {
                tap: 'filter_finished_orders'
            },
            "new_orders": {
                tap: 'filter_new_orders'
            },
            "all_orders": {
                tap: 'filter_all_orders'
            },
            "closed_orders": {
                tap: 'filter_closed_orders'
            }
        }
    },

    filter_finished_orders: function(button, e, eOpts) {
        var store = this.getSearchOrderMenu().source_store;
        var status_store = this.getSearchOrderMenu().status_store;

        store.clearFilter();

        store.filter('id_status', status_store.findRecord('name', 'Заказ готов', 0, false, false, true).get('id_status'));

        this.getSearchOrderMenu().destroy();


    },

    filter_new_orders: function(button, e, eOpts) {
        var store = this.getSearchOrderMenu().source_store;
        var status_store = this.getSearchOrderMenu().status_store;

        store.clearFilter();

        store.filter('id_status', status_store.findRecord('name', 'Заказ создан', 0, false, false, true).get('id_status'));

        this.getSearchOrderMenu().destroy();


    },

    filter_all_orders: function(button, e, eOpts) {
        var store = this.getSearchOrderMenu().source_store;
        var status_store = this.getSearchOrderMenu().status_store;

        store.clearFilter();

        this.getSearchOrderMenu().destroy();


    },

    filter_closed_orders: function(button, e, eOpts) {
        var store = this.getSearchOrderMenu().source_store;
        var status_store = this.getSearchOrderMenu().status_store;

        store.clearFilter();

        store.filter('id_status', status_store.findRecord('name', 'Заказ закрыт', 0, false, false, true).get('id_status'));

        this.getSearchOrderMenu().destroy();
    }

});